//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);    initial catalog=CCLPharma_New;Persist Se" +
            "curity Info=True;User ID=sa;Password=Pakistan1234")]
        public string PocketDCRConnectionString {
            get {
                return ((string)(this["PocketDCRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);    initial catalog=CCLPharma_New;Persist Se" +
            "curity Info=True;User ID=sa")]
        public string PocketDCRConnectionString3 {
            get {
                return ((string)(this["PocketDCRConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);    initial catalog=CCLPharma_New;Persist Se" +
            "curity Info=True;User ID=sa;Password=Pakistan1234")]
        public string PocketDCRConnectionString1 {
            get {
                return ((string)(this["PocketDCRConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);    initial catalog=CCLPharma_New;Persist Se" +
            "curity Info=True;User ID=sa;Password=Pakistan1234")]
        public string PocketDCRConnectionString2 {
            get {
                return ((string)(this["PocketDCRConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);    initial catalog=CCLPharma_New;Persist Se" +
            "curity Info=True;User ID=sa;Password=Pakistan1234")]
        public string ServerConnectionString {
            get {
                return ((string)(this["ServerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);    initial catalog=CCLPharma_New;User ID=sa" +
            ";Password=Pakistan1234")]
        public string ServerConnectionString1 {
            get {
                return ((string)(this["ServerConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);    initial catalog=CCLPharma_New;User ID=sa" +
            ";Password=Pakistan1234")]
        public string ServerConnectionString2 {
            get {
                return ((string)(this["ServerConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local); initial catalog=CCLPharma_New;Persist Secur" +
            "ity Info=True;User ID=sa;Password=Pakistan1234")]
        public string mycrmdConnectionString {
            get {
                return ((string)(this["mycrmdConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);  Initial Catalog=Pcrm;Integrated Security=True")]
        public string PcrmConnectionString {
            get {
                return ((string)(this["PcrmConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);initial catalog=CCLPharma_New;User ID=sa")]
        public string mycrmdNewDataConnectionString {
            get {
                return ((string)(this["mycrmdNewDataConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=mycrmdNewData;Persist Security Info=True;User" +
            " ID=sa;Password=Pakistan1234")]
        public string mycrmdNewDataConnectionString1 {
            get {
                return ((string)(this["mycrmdNewDataConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);initial catalog=CCLPharma_New;User ID=sa")]
        public string PBGMYCRMDConnectionString {
            get {
                return ((string)(this["PBGMYCRMDConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);initial catalog=CCLPharma_New;User ID=sa;Pas" +
            "sword=Pakistan1234")]
        public string PBGCRMConnectionString {
            get {
                return ((string)(this["PBGCRMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.0.148;initial catalog=CCLPharma_NewTemp;User " +
            "ID=sa")]
        public string CCLPharmaTempConnectionString {
            get {
                return ((string)(this["CCLPharmaTempConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);initial catalog=CCLPharma_New;Persist Securi" +
            "ty Info=True;User ID=sa;Password=Pakistan1234;MultipleActiveResultSets=True;Appl" +
            "ication Name=EntityFramework")]
        public string CCLPharmaConnectionString {
            get {
                return ((string)(this["CCLPharmaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);initial catalog=CCLPharma_New;User ID=sa;Pas" +
            "sword=Pakistan1234")]
        public string CCLPharma_ActiveDeactiveLevel4ConnectionString {
            get {
                return ((string)(this["CCLPharma_ActiveDeactiveLevel4ConnectionString"]));
            }
        }
    }
}
